### ISSUE TITLE
Software will not compile on OpenBSD 7.0

### ISSUE THREAD

**Issue by kintarowonders** [darkk/redsocks#165]
I am trying to get redsocks running on OpenBSD 7.0 but there are errors which prevent it from building. The errors claim my system is missing a simple type u_char and at a first glance, I think this is a pretty big problem.

Anyway, here are the errors from GCC after I ran 'gmake' to compile the latest master branch from Github...

```
usr/include/event.h:729:2: error: unknown type name 'u_char'; did you mean 'char'?
        u_char *buffer;
        ^
/usr/include/event.h:730:2: error: unknown type name 'u_char'; did you mean 'char'?
        u_char *orig_buffer;
        ^
/usr/include/event.h:1148:1: error: unknown type name 'u_char'; did you mean 'char'?
u_char *evbuffer_find(struct evbuffer *, const u_char *, size_t);
^
/usr/include/event.h:1148:48: error: unknown type name 'u_char'; did you mean 'char'?
```
I suspect I may be able to build some dependency here and have it use /usr/local/include/event.h here instead or something.
