### ISSUE TITLE
Can't Compile on OpenBSD 5.4

### ISSUE THREAD

**Issue by renaudallard** [darkk/redsocks#47]
Hello,

It seems the code is not compatible with recent OpenBSD version (note that I didn't try with older versions).

cc -g -O2 -std=gnu99 -Wall   -c -o parser.o parser.c
parser.c: In function 'vp_in_addr':
parser.c:304: error: 'AI_ADDRCONFIG' undeclared (first use in this function)
parser.c:304: error: (Each undeclared identifier is reported only once
parser.c:304: error: for each function it appears in.)
gmake: **\* [parser.o] Error 1
